SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE "2022-05%"
GROUP BY A.PRODUCT_ID
ORDER BY SUM(A.PRICE * B.AMOUNT) DESC, A.PRODUCT_ID
