SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF (FREEZER_YN IS NULL, 'N', FREEZER_YN) AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE "%경기%";
# SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
# FROM FOOD_WAREHOUSE
# WHERE WAREHOUSE_NAME LIKE "%경기%";
